# Generated by Django 5.0.3 on 2024-04-13 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='todoDescription',
            field=models.CharField(max_length=500, verbose_name=''),
        ),
    ]
